services:
  snipy:
    image: amirdaaee/snipy:latest
    container_name: snipy
    ports:
    - 80:80
    - 443:443
    environment:
      SNIPY__LOCAL_IP: 0.0.0.0
      SNIPY__WORKERS: 10
      LOGURU_LEVEL: 'INFO'
    restart: unless-stopped